### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Extended#123]
- [x] Toxic Water drip particle
- [x] Candle & Skull candle models
- [ ] Spawners models
- [x] Pile of bones models
- [ ] Bone fishing pole thread renderring
- [ ] Skull crawlers rotation on walls
- [ ] Put zombies, skeletons and other corpses to some graves
- [ ] Merge skull & candle models in Skullcandle model for spawners
- [ ] Bone Wings
- [ ] Bone Pickaxe enchantment
- [ ] Bone Shovel enchantment
- [ ] Possessed Armor drop ?
