### ISSUE TITLE
Potions / Effects

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Extended#67]
- [ ] Curse -> no potion  #11
- [x] Purification -> Awkward potion + Golden Koi #43
- [x] Bone Skin -> Awkward potion + Bonefish #64
- [x] Rust -> Awkward potion + Toxic Slime #64 
- [x] Bleeding -> Awkward potion + Piranha
- [x] Recall -> Awkward potion + Specular Fish #80
- [x] Burning Potion -> Awkward potion + Magma Jellyfish
- [x] Burning Inferno -> Burning Potion +  **????**
- [ ] Cursed Flame -> Awkward potion + Cursed Koi
- [ ] Cursed Inferno -> Cursed Flame Potion +  **????**
- [ ] Obstruction -> Awkward potion + Green Jellyfish
- [ ] Broken Armor -> **????**
- [ ] Thorns -> **????**
- [ ] Madness -> **????**
- [ ] Plague -> **????**
- [ ] Vampiric Touch -> **????**
- [ ] Moon Bite -> no potion #81
- [x] Breathlessness -> Water Breathing potion + piece of diving suit #177 #85 
- [ ] ?

Add recipes for vanilla potions:
- [x] Luck -> Awkward potion + Clown Fish
- [x] Hunger -> Awkward potion + Rotten Flesh
- [x] Nausea -> Awkward potion + Blue Jellyfish
- [x] Blindness -> Awkward potion + Spookyfin
- [x] Absorption -> Awkward potion + Cavefish
- [x] Levitation -> Awkward potion + Chorus Koi
- [ ] Bad Lick -> **????**
- [ ] Fatigue -> **????**
- [x] Wither(Decay) -> Awkward potion + Withered Crucian
