### ISSUE TITLE
Bone Fishing Pole

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Extended#70]
Add Bone Fishing Pole, which can be used for fishing in the toxic water.
It should be possible to enchant it with new enchantment - "Hellish Angling", which should allows to fishing in the lava.

**TODO**:
- [x] Bone Fishing Pole
- [x] Fishing in the Toxic Water
- [x] Hellish Angling enchantment and fishing in the lava
- [x] Catch should not burns at fishing in the lava

New fisherman's catch in water:
- [x] Blue Jellyfish
- [x] Specular Fish  (at the level of 50 blocks or deeper in the caves)
- [x] Frost Minnow (in cold biomes)
- [x] Piranha (in jungles)
- [x] Mud Tuna (in swamps)
- [x] Golden Koi (in desert)
- [x] Enderfin (in the End)
- [x] Pearl Bass (in the End / rare)
- [x] Chorus Koi (in the End / very rare)
- [x] Cavefish  (at the level of 40 blocks or deeper in the caves)
- [x] Angler Fish (at the level of 25 blocks or deeper in the caves)
- [x] Explosive Crucian
- [x] Ruffe (in swamps)
- [x] Sparkling Eel (in jungles)
- [x] Angelfish (in ocean)
- [x] Sponge Eater (in deep ocean)
- [x] Snowy Crucian (in cold biomes)
- [x] Squid
- [x] Sandy Bass (in desert)

New fisherman's catch in toxic water:
- [x] Bone (junk)
- [x] Rotten Flesh (junk)
- [x] Spider Eye (junk)
- [x] Bonefish
- [x] Green Jellyfish
- [x] Spookyfin 
- [x] Cursed Koi 
- [x] Skeleton and Zombie Skulls (treasure)
- [x] Enchanted Skull (treasure)

New fisherman's catch in lava:
- [x] Obsidifish 
- [x] Magma Jellyfish (rare)
- [x] Flarefin Koi (only in Nehter)
- [x] Nether Salmon  (only in Nehter)
- [x] Quartz Cod (only in Nehterr / rare)
- [x] Blaze Cod (only in Nehter / very rare)
- [x] Withered Crucian
- [x] Wither Skeleton Skull (treasure)
- [x] Withered Enchanted Skull (treasure)

Recipes for new fishes:
- [x] Bonefish -> 1 Pile of Bones
- [x] Green Jellyfish - > 3 Toxic Slime
- [x] Mud Tuna - > 4 Clay Balls
- [x] Sandy Bass - > 1 Sand
- [x] Magma Jellyfish -> 1 Magma Cream
- [x] Magma Jellyfish + Bucket -> Bucket of Lava
- [x] Nether Salmon - > 1 Netherrack
- [x] Flarefin Koi - > 2 Glowstone Dust
- [x] Quartz Cod - > 4 Quartz
- [x] Blaze Cod - > 1 Blaze Rod
- [x] Enderfin - > 1 Ender Stone
- [x] Pearl Bass - > 1 Ender Pearl
- [x] Chorus Koi - > 1 Chorus Fruit
- [x] 4 Obsidifish - > 1 Obsidian block
- [x] 4 Sponge Eater - > 1 Sponge block
- [x] Snowy Crucian - > 4 Snowbals
- [x] Squid - > 5 black dye
- [x] Explosive Crucian - > 3 gunpowder
- [x] 4 Frost Minnow - > Ice block
- [x] 2 Frost Minnow + 2 Ice block - > 2 Packed Ice block
- [x] 4 Withered Crucian - > Soul sand block
- [ ] Angler Fish  **????**

Furnace recipes:
- [x] Any fish - > Cooked Salmon 

Usage in potions #67 :
Specular Fish - > Recall Potion
Bonefish -> Bone Skin Potion
Piranha -> Bleeding Potion
Blue Jellyfish - > Nausea Potion
Green Jellyfish -> Obstruction
Cursed Koi -> Cursed Flame Potion
Magma Jellyfish -> Burning Potion
Spookyfin -> Blindness Potion
Golden Koi -> Potion of Purification
**????**

**Comment by NightKosh** [comment]
![blue_jellyfish](https://user-images.githubusercontent.com/4181327/34214004-24246e40-e5b2-11e7-864d-a52cd547803e.png)
![green_jellyfish](https://user-images.githubusercontent.com/4181327/34214005-245a2a08-e5b2-11e7-857e-fe60aef989ce.png)
![magma_jellyfish](https://user-images.githubusercontent.com/4181327/34214006-2476049e-e5b2-11e7-9da1-7d638637679d.png)
